"""Deterministic fixtures, deliberately labelled; never substituted for live failures."""
from html import escape
from .schemas import OUTPUTS


def generate_demo(stage, project, context):
    title = project['title']
    banner = '> Demo artifact: this fixed example validates the workflow. It did not call a model or perform live web research.\n\n'
    if stage == 'organize':
        data = dict(markdown=f'{banner}# {title}\n\n## Original idea\n{project["idea"]}\n\n## Constraints\n{project["constraints"] or "Time, budget, and existing skills still need to be defined."}\n\n## Problem and users\nAssumption: an individual builder needs a small application that validates the core workflow.\n\n## Goals and acceptance criteria\n- FR-001: Add and save a record.\n- FR-002: View and filter records.\n- FR-003: Export data.\n\n## Non-goals\nMulti-user collaboration, commercial payments, and complex permissions are outside the initial scope.', assumptions=['This is a fixed demo template, not a completed analysis of the submitted idea.', 'Assume one builder and prioritize validation of the core workflow.'], search_terms=[title + ' similar projects', title + ' open source'])
    elif stage == 'research':
        data = dict(markdown=banner + '# Research and differentiation\n\nLive mode will show comparable products, open-source projects, and source material here. Demo mode performs no search, so it cannot assess novelty.\n\n## Demo recommendation\nGO is used only to demonstrate the downstream workflow. A real project must first validate user demand, data availability, and differentiation.', recommendation='GO', rationale='Continue the demo workflow; this is not a real feasibility conclusion.', comparisons=[dict(name='Comparable solution to research', overlap='The core workflow may overlap; this has not been verified.', difference='Live research and user feedback are needed to establish differentiation.', evidence='Unknown', source_urls=[])], uncertainty=['Web Search was not run.', 'Competition, licensing, and cost remain unverified.'])
    elif stage == 'functions':
        names = [('Add and save', 'MVP', [], 1, 2, 3), ('View and filter', 'MVP', ['FL-001'], 1, 1.5, 2.5), ('Export data', 'Standard', ['FL-001'], .5, 1, 2)]
        functions = [dict(id=f'FL-{i:03}', name=n, value='Helps the user complete the core record workflow.', requirement=f'FR-{i:03}', tier=t, dependencies=d, low_days=lo, likely_days=li, high_days=hi, risk='Demo estimate; actual scope and integration complexity are unverified.') for i, (n, t, d, lo, li, hi) in enumerate(names, 1)]
        data = dict(markdown=banner + '# Functions and effort\n\nThe MVP focuses on adding, saving, and filtering records. Export is Standard scope.\n\nEstimates assume one person working sequentially in eight-hour days and include basic testing. Person-days are not calendar days; operating costs are excluded.', functions=functions, daily_rate=200, currency='USD', assumptions=['The 200 USD daily rate is a demo assumption, not a market quote.', 'Demo functions are fixed; Live mode generates them from the project context.'])
    elif stage == 'prototype':
        html = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:16px system-ui;background:#f5f4ee;color:#223f37;margin:0;padding:32px}main{max-width:680px;margin:auto}label{display:block;margin:18px 0 6px}input,button{font:inherit;padding:12px;border:1px solid #c6d0c4;border-radius:8px}input{width:65%}button{background:#234f41;color:white;cursor:pointer}li{padding:14px;background:white;margin:10px 0;border-radius:8px}small{color:#647269}#notice{min-height:24px}</style></head><body><main><small>Interactive prototype · demo data · resets on refresh</small><h1>__TITLE__</h1><p>Validate adding, saving, and finding records with a minimal flow.</p><form id="entry" data-function-id="FL-001"><label for="name">Record</label><input id="name" required maxlength="100" placeholder="Enter your first record"><button>Add</button></form><p id="notice" role="status"></p><section data-function-id="FL-002"><label for="filter">Filter records</label><input id="filter" placeholder="Enter a keyword"><ul id="items"></ul><p id="empty">No records yet. Add your first one.</p></section><small>FL-003 Export: Standard scope, not implemented in this prototype.</small></main><script>const rows=[];const form=document.querySelector('#entry'),nameInput=document.querySelector('#name'),filter=document.querySelector('#filter'),list=document.querySelector('#items');function render(){list.replaceChildren();const found=rows.filter(x=>x.includes(filter.value));for(const row of found){const li=document.createElement('li');li.textContent=row;list.append(li)}document.querySelector('#empty').hidden=found.length>0;document.querySelector('#empty').textContent=rows.length?'No matching records.':'No records yet. Add your first one.'}form.addEventListener('submit',e=>{e.preventDefault();if(!nameInput.value.trim())return;rows.push(nameInput.value.trim());nameInput.value='';document.querySelector('#notice').textContent='Saved for this prototype session (mock persistence).';render()});filter.addEventListener('input',render);</script></body></html>'''.replace('__TITLE__', escape(title))
        data = dict(markdown=banner + '# Prototype map\n\n- FL-001: The form adds a record; persistence is mocked in session memory.\n- FL-002: The list supports interactive keyword filtering.\n- FL-003: Standard export is deferred.\n\nThe generated prototype does not implement a real backend, authentication, or persistent storage.', html=html, mappings=[dict(function_id='FL-001', implementation='Form submission with in-memory mock persistence', behavior='mocked'), dict(function_id='FL-002', implementation='Immediate list filtering', behavior='interactive'), dict(function_id='FL-003', implementation='Deferred to Standard scope', behavior='deferred')])
    else:
        data = dict(markdown=banner + '# Architecture\n\n## Data flow\nBrowser → application API → SQLite. The export endpoint reads from the same database.\n\n## Deployment and boundaries\nA single-host deployment is enough to validate the MVP. Before public deployment, add authentication, server-side validation, database backups, and HTTPS.\n\n## Plan and evidence\n1. Implement the record API and persistence.\n2. Connect filtering and validate input boundaries.\n3. Implement export and measure task completion time.\n\nCurrent status: Designed / Prototype. There is no real-user, performance, or deployment evidence yet.', mermaid='flowchart LR\n  User[User] --> UI[Browser UI]\n  UI --> API[Application API]\n  API --> DB[(SQLite)]\n  API --> Export[Export module]', components=[dict(name='Browser UI', function_ids=['FL-001', 'FL-002'], responsibility='Input and filtering'), dict(name='Application API + SQLite', function_ids=['FL-001', 'FL-002', 'FL-003'], responsibility='Validation, persistence, queries, and export')], tradeoffs=['SQLite simplifies local deployment; reassess migration if multi-user write demand appears.', 'The example has no authentication; add it before any public deployment.'])
    return OUTPUTS[stage].model_validate(data)
